version: "3.8"

services:
  db:
    image: "postgres:latest"
    container_name: api-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${JOURNEY_DATABASE_USER}
      POSTGRES_DB: ${JOURNEY_DATABASE_NAME}
      POSTGRES_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - journey

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
  #   ports:
  #     - 8081:80
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   networks:
  #     - journey

  app:
    build: .
    container_name: api
    ports:
      - 8080:8080
    environment:
      JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME}
      JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER}
      JOURNEY_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      JOURNEY_DATABASE_PORT: ${JOURNEY_DATABASE_PORT:-5432}
      JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST_DOCKER:-db}
    depends_on:
      - db
    networks:
      - journey

networks:
  journey:
    driver: bridge

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
