name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker image
      run: docker build -t thauam09/nlw-journey-api-devops:${{ steps.generate_sha.outputs.sha }} .

    - name: Push image
      run: |
        docker push thauam09/nlw-journey-api-devops:${{ steps.generate_sha.outputs.sha }}
        docker tag thauam09/nlw-journey-api-devops:${{ steps.generate_sha.outputs.sha }} thauam09/nlw-journey-api-devops:latest
        docker push thauam09/nlw-journey-api-devops:latest